baseURL: http://example.org/
languageCode: en-us
title: &title ydnar.dev

taxonomies:
  tag: "tags"

pygmentsUseClasses: true
pygmentsCodeFences: true

params:
  dateFormat: Jan 2, 2006
  socialIcons:
    - name: github
      url: https://github.com/Starchery
    - name: email
      url: mailto:randolph.henry.work@gmail.com
    - name: linkedin
      url: https://www.linkedin.com/in/randolph-henry-a5073714b/

menu:
  main:
    - name: blogs
      pre: edit
      url: /blog/
      weight: 2

    - name: tags
      pre: tag
      url: /tags/
      weight: 3

    - name: projects
      pre: box
      url: /projects/
      weight: 4

    - name: about
      pre: user
      url: /about/
      weight: 5
