baseURL: http://example.org/
languageCode: en-us
title: &title ydnar.dev

taxonomies:
  tag: "tags"

params:
  dateFormat: Jan 2, 2006

markup:
  highlight:
    lineNos: true
    style: trac


menu:
  main:
    - name: *title
      pre: home
      url: /
      weight: 1

    - name: blogs
      pre: edit
      url: /blog/
      weight: 2

    - name: tags
      pre: tag
      url: /tags/
      weight: 3

    - name: projects
      pre: box
      url: /projects/
      weight: 4

    - name: about
      pre: user
      url: /about/
      weight: 5
