baseURL: http://example.org/
languageCode: en-us
title: &title ydnar.dev

taxonomies:
  tag: "tags"

pygmentsUseClasses: true
pygmentsCodeFences: true

params:
  dateFormat: Jan 2, 2006
  socialIcons:
    - name: github
      url: "https://github.com/adityatelange/hugo-PaperMod"
    - name: twitter
      url: "https://twitter.com/thateasyfolks"
    - name: email
      url: "mailto:randolph.henry.work@gmail.com"

markup:
  highlight:
    # style: friendly
  # tableOfContents:
  #   ordered: true

menu:
  main:
    - name: blogs
      pre: edit
      url: /blog/
      weight: 2

    - name: tags
      pre: tag
      url: /tags/
      weight: 3

    - name: projects
      pre: box
      url: /projects/
      weight: 4

    - name: about
      pre: user
      url: /about/
      weight: 5
